server:
  port: 8040

#eureka:
#  client:
#    service-url:
#      defaultZone: http://www.aishenhuo.wang:8000/eureka/,http://www.aishenhuo.wang:8001/eureka/,http://www.aishenhuo.wang:8002/eureka/

spring:
  application:
    name: ad-conf-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangjiangtao1986/ad-conf-center/
          search-paths: config-repo
          username: 375410692@163.com
          password: Password1986